cause_names = {
    "Animals": [
        "Animal Rights",  
        "Welfare, and Services",
        "Welfare and Services", "Wildlife Conservation",
        "Zoos And Aquariums",
        "Veterinary Services",
    ],
      "Arts, Culture, Humanities":[
         "Libraries",
        "Historical Societies and Landmark Preservation",
        "Museums",
        "Performing Arts",
        "Public Broadcasting and Media",
        "Service and Other",
    ],

    "Arts": [
        "Libraries",
        "Historical Societies and Landmark Preservation",
        "Museums",
        "Performing Arts",
        "Public Broadcasting and Media",
        "Service and Other",
    ],
    "Culture": [
        "Libraries",
        "Historical Societies and Landmark Preservation",
        "Museums",
        "Performing Arts",
        "Public Broadcasting and Media",
        "Service and Other",
    ],

    "Humanities": [
        "Libraries",
        "Historical Societies and Landmark Preservation",
        "Libraries, Historical Societies and Landmark Preservation",
        "Museums",
        "Performing Arts",
        "Public Broadcasting and Media",
        "Service and Other",
    ],
    "Community Development": [
        "United Ways",
        "Jewish Federations",
        "Community Foundations",
        "Community Improvement",
        "Housing and Neighborhood Development",
    ],
    "Education": [
        "Early Childhood Programs and Services",
        "Youth Education Programs and Services",
        "Adult Education Programs and Services",
        "Special Education",
        "Education Policy and Reform",
        "Scholarship and Financial Support",
        "College and University",
        "Voter Education and Registration",
    ],
    "Environment": [
        "Environmental Protection and Conservation",
        "Botanical Gardens, Parks, and Nature Centers",
        "Botanical Gardens", "Parks", "Nature Centers",
        "Pollution",
    ],
    "Health": [
        "Diseases, Disorders, and Disciplines",
        "Diseases", "Disorders", "Disciplines",
        "Diseases", "Disorders, and Disciplines",
        "Patient and Family Support",
        "Treatment and Prevention Services",
        "Medical Research",
        "Addiction and Substance Abuse",
        "Medical Disciplines and Specialty Research",
        "Mental Health and Crisis Serices",
    ],
    "Human Services": [
        "Children's and Family Services",
        "Youth Development, Shelter, and Crisis Services",
        "Food Banks, Food Pantries, and Food Distribution",
        "Multipurpose Human Service Organizations",
        "Homeless Services",
        "Social Services",
        "General Human Services",
        "Agriculture",
        "Food and Nutrition",
        "Crime and Legal Related",
        "Public Safety",
        "Disaster Preparedness, and Relief",
        "Recreation and Sports",
        "Mutual",
        "Membership Benefit Organization",
    ],
    "International": [
        "Poverty",
        "Development and Relief Services" "International Peace",
        "Security, and Affairs",
        "Humanitarian Relief Supplies",
        "Human Rights",
        "Civil Rights and Liberties"],
        "Research & Public Policy":[
        "Non-Medical Science & Technology Research",
        "Social and Public Policy Research",
        "Research Institutes"],

    "Religion": [
        "Religious Activities, General",
        "Christian",
        "Hindu",
        "Islamic",
        "Jewish",
        "Religious Media and Broadcasting",
    ],
    "Unknown": ["Unclassified"],
}



countries = [
    "India",
    "United States of America",
    "Pakistan",
    "Nigeria",
    "Philippines",
    "United Kingdom",
    "Tanzania",
    "South Africa",
    "Kenya",
    "Uganda",
    "Canada",
    "Ghana",
    "Cameroon",
    "Australia",
    "Malawi",
    "Zambia",
    "Zimbabwe",
    "Rwanda",
    "Burundi",
    "South Sudan",
    "Dominican Republic",
    "Papua New Guinea",
    "Sierra Leone",
    "Singapore",
    "Liberia",
    "Ireland",
    "New Zealand",
    "Eritrea",
    "Jamaica",
    "Namibia",
    "Gambia",
    "Botswana",
    "Lesotho",
    "Trinidad",
    "Tobago",
    "Mauritius",
    "Eswatini",
    "Swaziland",
    "Fiji",
    "Guyana",
    "Solomon Islands",
    "Micronesia",
    "Malta",
    "Belize",
    "Bahamas",
    "Barbados",
    "Samoa",
    "Saint Lucia",
    "Kiribati",
    "Grenada",
]

if __name__ == "__main__":
    print(countries)
    print(cause_names)