countries = [
    "India",
    "United States of America",
    "Pakistan",
    "Nigeria",
    "Philippines",
    "United Kingdom",
    "Tanzania",
    "South Africa",
    "Kenya",
    "Uganda",
    "Canada",
    "Ghana",
    "Cameroon",
    "Australia",
    "Malawi",
    "Zambia",
    "Zimbabwe",
    "Rwanda",
    "Burundi",
    "South Sudan",
    "Dominican Republic",
    "Papua New Guinea",
    "Sierra Leone",
    "Singapore",
    "Liberia",
    "Ireland",
    "New Zealand",
    "Eritrea",
    "Jamaica",
    "Namibia",
    "Gambia",
    "Botswana",
    "Lesotho",
    "Trinidad",
    "Tobago",
    "Mauritius",
    "Eswatini",
    "Swaziland",
    "Fiji",
    "Guyana",
    "Solomon Islands",
    "Micronesia",
    "Malta",
    "Belize",
    "Bahamas",
    "Barbados",
    "Samoa",
    "Saint Lucia",
    "Kiribati",
    "Grenada",
]
